### PR TITLE
Fixes callback error handling

### LINKED ISSUE #32: Callbacks called twice when containing errors
When the callback provided to `batch.end` throws an error things can go a bit haywire... Here is an example I put together.

```javascript
const Batch = require('batch')
const batch = new Batch()

batch.push(cb => cb())
batch.push(cb => cb())
batch.push(cb => cb())

var i = 1;

batch.end(function(err) {
  console.log(i++)

  if(err) {
    console.log(err)
  }

  throw "Error"
})
```
Outputs

```
1
2
Error
```

This shows the callback being called twice,  once with no error (expected) and once with the error contained in the callback! After doing a bit of digging I found the `try/catch` block in `index.js:117` to be the culprit. I assume this was put in so that synchronous type functions would produce callback style errors. It's a really messy bug to have though because it can catch all downstream errors of the callback.

### PR DESCRIPTION
**Pull request by Crazometer**
Fixes #32

### CODE REVIEW

**Comment by Crazometer** [comment]
Alternatively if you want to keep the try/catch the callback could be executed via a `setTimeout(callback, 0)` or `process.nextTick(callback)`

**Comment by dougwilson** [comment]
@tj I would be happy to take the reigns on this module and publish updates if you like. Just add me to the module on npm :)

**Comment by tj** [comment]
@dougwilson should be good to go!

**Comment by dougwilson** [comment]
> callback could be executed via a setTimeout(callback, 0) or process.nextTick(callback)

Yea, I think this is the best option for now, since that just makes calling `batch.end(cb)` always invoke `cb` in a future execution instead of it depending on what has been added to the batch.

**Pull request closed without merging**
